#!/bin/bash

# Check if 3cxpbx is already installed
if dpkg -s 3cxpbx &> /dev/null; then
    echo "3cxpbx already installed."
    exit 0
fi

# Detect Debian version
DEBIAN_VERSION=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2)

# Common installations
apt install sudo lsb-release gnupg2 wget curl -y

# Function to update apt
update() {
    while fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
        sleep 1
    done
    while ! apt update; do
        sleep 5
    done
}

# Add 3CX repo and key based on Debian version
if [ "$DEBIAN_VERSION" == "10" ]; then
    echo "Detected Debian Buster (10)."
    wget -O- http://downloads-global.3cx.com/downloads/3cxpbx/public.key | apt-key add -
    echo "deb http://downloads-global.3cx.com/downloads/debian buster main" | tee /etc/apt/sources.list.d/3cxpbx.list
    apt install open-vm-tools net-tools dphys-swapfile -y
elif [ "$DEBIAN_VERSION" == "11" ]; then
    echo "Detected Debian Bullseye (11)."
    wget -O- https://repo.3cx.com/key.pub | apt-key add -
    echo "deb http://repo.3cx.com/3cx bullseye main" | tee /etc/apt/sources.list.d/3cxpbx.list
    apt install apt-transport-https coreutils inetutils-ping dphys-swapfile net-tools gpg nginx -y
else
    echo "Unsupported Debian version."
    exit 1
fi

# Update repositories
update

# Install 3CX
while ! DEBIAN_FRONTEND=noninteractive apt install 3cxpbx -y; do
    sleep 5
done

# Create file to indicate that 3cxpbx is installed
touch /etc/3cxpbx/pbxinstalled

# Done
echo "Done."
